// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  buttons: dynamic(() => import("./Buttons")),
  rich_text: dynamic(() => import("./RichText")),
};
